# Generated by Django 4.1.3 on 2024-03-28 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_rest", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutoVO",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vin", models.CharField(max_length=100)),
                ("import_href", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name="technician",
            old_name="employee_number",
            new_name="employee_id",
        ),
    ]
