# Generated by Django 4.1.3 on 2024-04-09 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_rest", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="automobile",
            name="model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory_rest.vehiclemodel",
            ),
        ),
    ]
